/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
#include <app-common/zap-generated/cluster-objects.h>
#include <app/util/af-enums.h>

typedef void (*CHIPDefaultSuccessCallbackType)(void *, const chip::app::DataModel::NullObjectType &);
typedef void (*CHIPDefaultWriteSuccessCallbackType)(void *);
typedef void (*CHIPDefaultFailureCallbackType)(void *, CHIP_ERROR);

typedef void (*CHIPIdentifyClusterIdentifyTimeAttributeCallbackType)(
    void *, chip::app::Clusters::Identify::Attributes::IdentifyTime::TypeInfo::DecodableArgType);
typedef void (*CHIPIdentifyClusterIdentifyTypeAttributeCallbackType)(
    void *, chip::app::Clusters::Identify::Attributes::IdentifyType::TypeInfo::DecodableArgType);
typedef void (*CHIPIdentifyClusterGeneratedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::Identify::Attributes::GeneratedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPIdentifyClusterAcceptedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::Identify::Attributes::AcceptedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPIdentifyClusterEventListAttributeCallbackType)(
    void *, const chip::app::Clusters::Identify::Attributes::EventList::TypeInfo::DecodableType &);
typedef void (*CHIPIdentifyClusterAttributeListAttributeCallbackType)(
    void *, const chip::app::Clusters::Identify::Attributes::AttributeList::TypeInfo::DecodableType &);
typedef void (*CHIPIdentifyClusterFeatureMapAttributeCallbackType)(
    void *, chip::app::Clusters::Identify::Attributes::FeatureMap::TypeInfo::DecodableArgType);
typedef void (*CHIPIdentifyClusterClusterRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::Identify::Attributes::ClusterRevision::TypeInfo::DecodableArgType);

typedef void (*CHIPDescriptorClusterDeviceTypeListAttributeCallbackType)(
    void *, const chip::app::Clusters::Descriptor::Attributes::DeviceTypeList::TypeInfo::DecodableType &);
typedef void (*CHIPDescriptorClusterServerListAttributeCallbackType)(
    void *, const chip::app::Clusters::Descriptor::Attributes::ServerList::TypeInfo::DecodableType &);
typedef void (*CHIPDescriptorClusterClientListAttributeCallbackType)(
    void *, const chip::app::Clusters::Descriptor::Attributes::ClientList::TypeInfo::DecodableType &);
typedef void (*CHIPDescriptorClusterPartsListAttributeCallbackType)(
    void *, const chip::app::Clusters::Descriptor::Attributes::PartsList::TypeInfo::DecodableType &);
typedef void (*CHIPDescriptorClusterGeneratedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::Descriptor::Attributes::GeneratedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPDescriptorClusterAcceptedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::Descriptor::Attributes::AcceptedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPDescriptorClusterEventListAttributeCallbackType)(
    void *, const chip::app::Clusters::Descriptor::Attributes::EventList::TypeInfo::DecodableType &);
typedef void (*CHIPDescriptorClusterAttributeListAttributeCallbackType)(
    void *, const chip::app::Clusters::Descriptor::Attributes::AttributeList::TypeInfo::DecodableType &);
typedef void (*CHIPDescriptorClusterFeatureMapAttributeCallbackType)(
    void *, chip::app::Clusters::Descriptor::Attributes::FeatureMap::TypeInfo::DecodableArgType);
typedef void (*CHIPDescriptorClusterClusterRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::Descriptor::Attributes::ClusterRevision::TypeInfo::DecodableArgType);

typedef void (*CHIPAccessControlClusterAclAttributeCallbackType)(
    void *, const chip::app::Clusters::AccessControl::Attributes::Acl::TypeInfo::DecodableType &);
typedef void (*CHIPAccessControlClusterExtensionAttributeCallbackType)(
    void *, const chip::app::Clusters::AccessControl::Attributes::Extension::TypeInfo::DecodableType &);
typedef void (*CHIPAccessControlClusterSubjectsPerAccessControlEntryAttributeCallbackType)(
    void *, chip::app::Clusters::AccessControl::Attributes::SubjectsPerAccessControlEntry::TypeInfo::DecodableArgType);
typedef void (*CHIPAccessControlClusterTargetsPerAccessControlEntryAttributeCallbackType)(
    void *, chip::app::Clusters::AccessControl::Attributes::TargetsPerAccessControlEntry::TypeInfo::DecodableArgType);
typedef void (*CHIPAccessControlClusterAccessControlEntriesPerFabricAttributeCallbackType)(
    void *, chip::app::Clusters::AccessControl::Attributes::AccessControlEntriesPerFabric::TypeInfo::DecodableArgType);
typedef void (*CHIPAccessControlClusterGeneratedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::AccessControl::Attributes::GeneratedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPAccessControlClusterAcceptedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::AccessControl::Attributes::AcceptedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPAccessControlClusterEventListAttributeCallbackType)(
    void *, const chip::app::Clusters::AccessControl::Attributes::EventList::TypeInfo::DecodableType &);
typedef void (*CHIPAccessControlClusterAttributeListAttributeCallbackType)(
    void *, const chip::app::Clusters::AccessControl::Attributes::AttributeList::TypeInfo::DecodableType &);
typedef void (*CHIPAccessControlClusterFeatureMapAttributeCallbackType)(
    void *, chip::app::Clusters::AccessControl::Attributes::FeatureMap::TypeInfo::DecodableArgType);
typedef void (*CHIPAccessControlClusterClusterRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::AccessControl::Attributes::ClusterRevision::TypeInfo::DecodableArgType);

typedef void (*CHIPBasicInformationClusterDataModelRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::DataModelRevision::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterVendorNameAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::VendorName::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterVendorIDAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::VendorID::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterProductNameAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::ProductName::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterProductIDAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::ProductID::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterNodeLabelAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::NodeLabel::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterLocationAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::Location::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterHardwareVersionAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::HardwareVersion::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterHardwareVersionStringAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::HardwareVersionString::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterSoftwareVersionAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::SoftwareVersion::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterSoftwareVersionStringAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::SoftwareVersionString::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterManufacturingDateAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::ManufacturingDate::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterPartNumberAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::PartNumber::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterProductURLAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::ProductURL::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterProductLabelAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::ProductLabel::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterSerialNumberAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::SerialNumber::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterLocalConfigDisabledAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::LocalConfigDisabled::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterReachableAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::Reachable::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterUniqueIDAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::UniqueID::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterCapabilityMinimaAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::CapabilityMinima::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterGeneratedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::BasicInformation::Attributes::GeneratedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPBasicInformationClusterAcceptedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::BasicInformation::Attributes::AcceptedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPBasicInformationClusterEventListAttributeCallbackType)(
    void *, const chip::app::Clusters::BasicInformation::Attributes::EventList::TypeInfo::DecodableType &);
typedef void (*CHIPBasicInformationClusterAttributeListAttributeCallbackType)(
    void *, const chip::app::Clusters::BasicInformation::Attributes::AttributeList::TypeInfo::DecodableType &);
typedef void (*CHIPBasicInformationClusterFeatureMapAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::FeatureMap::TypeInfo::DecodableArgType);
typedef void (*CHIPBasicInformationClusterClusterRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::BasicInformation::Attributes::ClusterRevision::TypeInfo::DecodableArgType);

typedef void (*CHIPLocalizationConfigurationClusterActiveLocaleAttributeCallbackType)(
    void *, chip::app::Clusters::LocalizationConfiguration::Attributes::ActiveLocale::TypeInfo::DecodableArgType);
typedef void (*CHIPLocalizationConfigurationClusterSupportedLocalesAttributeCallbackType)(
    void *, const chip::app::Clusters::LocalizationConfiguration::Attributes::SupportedLocales::TypeInfo::DecodableType &);
typedef void (*CHIPLocalizationConfigurationClusterGeneratedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::LocalizationConfiguration::Attributes::GeneratedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPLocalizationConfigurationClusterAcceptedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::LocalizationConfiguration::Attributes::AcceptedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPLocalizationConfigurationClusterEventListAttributeCallbackType)(
    void *, const chip::app::Clusters::LocalizationConfiguration::Attributes::EventList::TypeInfo::DecodableType &);
typedef void (*CHIPLocalizationConfigurationClusterAttributeListAttributeCallbackType)(
    void *, const chip::app::Clusters::LocalizationConfiguration::Attributes::AttributeList::TypeInfo::DecodableType &);
typedef void (*CHIPLocalizationConfigurationClusterFeatureMapAttributeCallbackType)(
    void *, chip::app::Clusters::LocalizationConfiguration::Attributes::FeatureMap::TypeInfo::DecodableArgType);
typedef void (*CHIPLocalizationConfigurationClusterClusterRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::LocalizationConfiguration::Attributes::ClusterRevision::TypeInfo::DecodableArgType);
typedef void (*CHIPGeneralCommissioningClusterArmFailSafeResponseCallbackType)(
    void *, const chip::app::Clusters::GeneralCommissioning::Commands::ArmFailSafeResponse::DecodableType &);
typedef void (*CHIPGeneralCommissioningClusterSetRegulatoryConfigResponseCallbackType)(
    void *, const chip::app::Clusters::GeneralCommissioning::Commands::SetRegulatoryConfigResponse::DecodableType &);
typedef void (*CHIPGeneralCommissioningClusterCommissioningCompleteResponseCallbackType)(
    void *, const chip::app::Clusters::GeneralCommissioning::Commands::CommissioningCompleteResponse::DecodableType &);

typedef void (*CHIPGeneralCommissioningClusterBreadcrumbAttributeCallbackType)(
    void *, chip::app::Clusters::GeneralCommissioning::Attributes::Breadcrumb::TypeInfo::DecodableArgType);
typedef void (*CHIPGeneralCommissioningClusterBasicCommissioningInfoAttributeCallbackType)(
    void *, chip::app::Clusters::GeneralCommissioning::Attributes::BasicCommissioningInfo::TypeInfo::DecodableArgType);
typedef void (*CHIPGeneralCommissioningClusterRegulatoryConfigAttributeCallbackType)(
    void *, chip::app::Clusters::GeneralCommissioning::Attributes::RegulatoryConfig::TypeInfo::DecodableArgType);
typedef void (*CHIPGeneralCommissioningClusterLocationCapabilityAttributeCallbackType)(
    void *, chip::app::Clusters::GeneralCommissioning::Attributes::LocationCapability::TypeInfo::DecodableArgType);
typedef void (*CHIPGeneralCommissioningClusterSupportsConcurrentConnectionAttributeCallbackType)(
    void *, chip::app::Clusters::GeneralCommissioning::Attributes::SupportsConcurrentConnection::TypeInfo::DecodableArgType);
typedef void (*CHIPGeneralCommissioningClusterGeneratedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::GeneralCommissioning::Attributes::GeneratedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPGeneralCommissioningClusterAcceptedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::GeneralCommissioning::Attributes::AcceptedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPGeneralCommissioningClusterEventListAttributeCallbackType)(
    void *, const chip::app::Clusters::GeneralCommissioning::Attributes::EventList::TypeInfo::DecodableType &);
typedef void (*CHIPGeneralCommissioningClusterAttributeListAttributeCallbackType)(
    void *, const chip::app::Clusters::GeneralCommissioning::Attributes::AttributeList::TypeInfo::DecodableType &);
typedef void (*CHIPGeneralCommissioningClusterFeatureMapAttributeCallbackType)(
    void *, chip::app::Clusters::GeneralCommissioning::Attributes::FeatureMap::TypeInfo::DecodableArgType);
typedef void (*CHIPGeneralCommissioningClusterClusterRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::GeneralCommissioning::Attributes::ClusterRevision::TypeInfo::DecodableArgType);
typedef void (*CHIPNetworkCommissioningClusterScanNetworksResponseCallbackType)(
    void *, const chip::app::Clusters::NetworkCommissioning::Commands::ScanNetworksResponse::DecodableType &);
typedef void (*CHIPNetworkCommissioningClusterNetworkConfigResponseCallbackType)(
    void *, const chip::app::Clusters::NetworkCommissioning::Commands::NetworkConfigResponse::DecodableType &);
typedef void (*CHIPNetworkCommissioningClusterConnectNetworkResponseCallbackType)(
    void *, const chip::app::Clusters::NetworkCommissioning::Commands::ConnectNetworkResponse::DecodableType &);

typedef void (*CHIPNetworkCommissioningClusterMaxNetworksAttributeCallbackType)(
    void *, chip::app::Clusters::NetworkCommissioning::Attributes::MaxNetworks::TypeInfo::DecodableArgType);
typedef void (*CHIPNetworkCommissioningClusterNetworksAttributeCallbackType)(
    void *, const chip::app::Clusters::NetworkCommissioning::Attributes::Networks::TypeInfo::DecodableType &);
typedef void (*CHIPNetworkCommissioningClusterScanMaxTimeSecondsAttributeCallbackType)(
    void *, chip::app::Clusters::NetworkCommissioning::Attributes::ScanMaxTimeSeconds::TypeInfo::DecodableArgType);
typedef void (*CHIPNetworkCommissioningClusterConnectMaxTimeSecondsAttributeCallbackType)(
    void *, chip::app::Clusters::NetworkCommissioning::Attributes::ConnectMaxTimeSeconds::TypeInfo::DecodableArgType);
typedef void (*CHIPNetworkCommissioningClusterInterfaceEnabledAttributeCallbackType)(
    void *, chip::app::Clusters::NetworkCommissioning::Attributes::InterfaceEnabled::TypeInfo::DecodableArgType);
typedef void (*CHIPNetworkCommissioningClusterLastNetworkingStatusAttributeCallbackType)(
    void *, chip::app::Clusters::NetworkCommissioning::Attributes::LastNetworkingStatus::TypeInfo::DecodableArgType);
typedef void (*CHIPNetworkCommissioningClusterLastNetworkIDAttributeCallbackType)(
    void *, chip::app::Clusters::NetworkCommissioning::Attributes::LastNetworkID::TypeInfo::DecodableArgType);
typedef void (*CHIPNetworkCommissioningClusterLastConnectErrorValueAttributeCallbackType)(
    void *, chip::app::Clusters::NetworkCommissioning::Attributes::LastConnectErrorValue::TypeInfo::DecodableArgType);
typedef void (*CHIPNetworkCommissioningClusterGeneratedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::NetworkCommissioning::Attributes::GeneratedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPNetworkCommissioningClusterAcceptedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::NetworkCommissioning::Attributes::AcceptedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPNetworkCommissioningClusterEventListAttributeCallbackType)(
    void *, const chip::app::Clusters::NetworkCommissioning::Attributes::EventList::TypeInfo::DecodableType &);
typedef void (*CHIPNetworkCommissioningClusterAttributeListAttributeCallbackType)(
    void *, const chip::app::Clusters::NetworkCommissioning::Attributes::AttributeList::TypeInfo::DecodableType &);
typedef void (*CHIPNetworkCommissioningClusterFeatureMapAttributeCallbackType)(
    void *, chip::app::Clusters::NetworkCommissioning::Attributes::FeatureMap::TypeInfo::DecodableArgType);
typedef void (*CHIPNetworkCommissioningClusterClusterRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::NetworkCommissioning::Attributes::ClusterRevision::TypeInfo::DecodableArgType);

typedef void (*CHIPAdministratorCommissioningClusterWindowStatusAttributeCallbackType)(
    void *, chip::app::Clusters::AdministratorCommissioning::Attributes::WindowStatus::TypeInfo::DecodableArgType);
typedef void (*CHIPAdministratorCommissioningClusterAdminFabricIndexAttributeCallbackType)(
    void *, chip::app::Clusters::AdministratorCommissioning::Attributes::AdminFabricIndex::TypeInfo::DecodableArgType);
typedef void (*CHIPAdministratorCommissioningClusterAdminVendorIdAttributeCallbackType)(
    void *, chip::app::Clusters::AdministratorCommissioning::Attributes::AdminVendorId::TypeInfo::DecodableArgType);
typedef void (*CHIPAdministratorCommissioningClusterGeneratedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::AdministratorCommissioning::Attributes::GeneratedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPAdministratorCommissioningClusterAcceptedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::AdministratorCommissioning::Attributes::AcceptedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPAdministratorCommissioningClusterEventListAttributeCallbackType)(
    void *, const chip::app::Clusters::AdministratorCommissioning::Attributes::EventList::TypeInfo::DecodableType &);
typedef void (*CHIPAdministratorCommissioningClusterAttributeListAttributeCallbackType)(
    void *, const chip::app::Clusters::AdministratorCommissioning::Attributes::AttributeList::TypeInfo::DecodableType &);
typedef void (*CHIPAdministratorCommissioningClusterFeatureMapAttributeCallbackType)(
    void *, chip::app::Clusters::AdministratorCommissioning::Attributes::FeatureMap::TypeInfo::DecodableArgType);
typedef void (*CHIPAdministratorCommissioningClusterClusterRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::AdministratorCommissioning::Attributes::ClusterRevision::TypeInfo::DecodableArgType);
typedef void (*CHIPOperationalCredentialsClusterAttestationResponseCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Commands::AttestationResponse::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterCertificateChainResponseCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Commands::CertificateChainResponse::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterCSRResponseCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Commands::CSRResponse::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterNOCResponseCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Commands::NOCResponse::DecodableType &);

typedef void (*CHIPOperationalCredentialsClusterNOCsAttributeCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Attributes::NOCs::TypeInfo::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterFabricsAttributeCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Attributes::Fabrics::TypeInfo::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterSupportedFabricsAttributeCallbackType)(
    void *, chip::app::Clusters::OperationalCredentials::Attributes::SupportedFabrics::TypeInfo::DecodableArgType);
typedef void (*CHIPOperationalCredentialsClusterCommissionedFabricsAttributeCallbackType)(
    void *, chip::app::Clusters::OperationalCredentials::Attributes::CommissionedFabrics::TypeInfo::DecodableArgType);
typedef void (*CHIPOperationalCredentialsClusterTrustedRootCertificatesAttributeCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Attributes::TrustedRootCertificates::TypeInfo::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterCurrentFabricIndexAttributeCallbackType)(
    void *, chip::app::Clusters::OperationalCredentials::Attributes::CurrentFabricIndex::TypeInfo::DecodableArgType);
typedef void (*CHIPOperationalCredentialsClusterGeneratedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Attributes::GeneratedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterAcceptedCommandListAttributeCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Attributes::AcceptedCommandList::TypeInfo::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterEventListAttributeCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Attributes::EventList::TypeInfo::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterAttributeListAttributeCallbackType)(
    void *, const chip::app::Clusters::OperationalCredentials::Attributes::AttributeList::TypeInfo::DecodableType &);
typedef void (*CHIPOperationalCredentialsClusterFeatureMapAttributeCallbackType)(
    void *, chip::app::Clusters::OperationalCredentials::Attributes::FeatureMap::TypeInfo::DecodableArgType);
typedef void (*CHIPOperationalCredentialsClusterClusterRevisionAttributeCallbackType)(
    void *, chip::app::Clusters::OperationalCredentials::Attributes::ClusterRevision::TypeInfo::DecodableArgType);
